### ISSUE TITLE
make && make run fails on generate-annot.sh

### ISSUE THREAD

**Issue by aniketp** [shivansh/smoketestsuite#22]
On running tests using `make && make run` as mentioned in `README`, I get this error
``` bash
Generating annotations...
sh /root/smoke/src/scripts/generate_annot.sh
kyua: E: No previous results file found for test suite usr_tests_bin_date.
```

**Comment by aniketp41** [comment]
Figured out the issue!
On running `kyua test -k /usr/tests/Kyuafile`. The generated tests somehow missed the path `/usr/tests/bin/date`.
I had to manually generate tests for that particular directory. On doing that, the `generate_annot.sh` works as expected.
@shivansh Please close the issue after you've seen it.
